### ISSUE TITLE
Startup Bug: Settings form Player box is disabled

### ISSUE THREAD

**Issue by ajTronic** [teshiba/AoE2.netDesktop#45]
**Describe the bug**
New developer cannot input ID. I think that this bug effects all new users, or at least new developers on this project. 

**To Reproduce**
1. On a new machine, open the code in Visual Studio. 
2. Run it
3. See error (screenshot below)

**Expected behavior**
The settings form player box should be enabled so that the user can input his ID.

**Screenshots**
![2022-07-27 11_23_04-AoE2 net Desktop](https://user-images.githubusercontent.com/83540738/181231031-8e0fa1f2-0fb5-4a79-97e1-34120fed5b45.png)

![2022-07-27 11_53_38-Untitled 1 - LibreOffice Draw](https://user-images.githubusercontent.com/83540738/181231086-b8f85f2c-8b3c-4635-88fd-ddf9a8ea056d.png)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by teshiba** [comment]
I find another reason for the issue.
The exception has occurred because an async HTTP request method calls a method, which accesses a GUI object.  

1: HTTP NotFound Exception occurred. But it is not the reason for the bug.
![image](https://user-images.githubusercontent.com/35426691/181508447-1233be74-5a85-4a26-9b5b-0b4b6100358c.png)

2: Refer to GUI label object from the async task that is not GUI context.
![image](https://user-images.githubusercontent.com/35426691/181508490-155b5068-e759-476f-9f4f-7b7a62c31418.png)

3: The problem is direct access to the label when InvokeRequired is true. And no one doesn't catch the exception properly.
![image](https://user-images.githubusercontent.com/35426691/181508519-758313a3-b4dc-4c57-ba20-977c36fda3d3.png)
